[cookie]
expiry_days = 1
key = "3f9c88f2-8a1b-4bb5-b33f-2a0e88d3cbee"
name = "cookie_ppcc"

[credentials]
usernames = {adminppcc = {email = "ppcc.dgf.uchile@gmail.com", name = "adminppcc", password = "ppccweb2024"}, lucasglasner = {email = "lgvivanco96@gmail.com", name = "Lucas Glasner", password = "kpt6yrnsRvVm"}}

